export const REQUEST_PATIENT = "REQUEST_PATIENT";
export const SUCCESS_PATIENT = "SUCCESS_PATIENT";
export const FAIL_PATIENT= "FAIL_PATIENT";

export const REQUEST_PATIENT_GROUP = "REQUEST_PATIENT_GROUP";
export const SUCCESS_PATIENT_GROUP = "SUCCESS_PATIENT_GROUP";
export const FAIL_PATIENT_GROUP= "FAIL_PATIENT_GROUP";

export const REQUEST_PATIENT_SINGLE = "REQUEST_PATIENT_SINGLE";
export const SUCCESS_PATIENT_SINGLE = "SUCCESS_PATIENT_SINGLE";
export const FAIL_PATIENT_SINGLE = "FAIL_PATIENT_SINGLE";

